/*Marco Beltempo
12/13/2017
DBS501AA*/

SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    V_FLAG        VARCHAR2(7);
    V_ZIP_COUNT   NUMBER;
BEGIN
    ADD_ZIP2('18104','Chicago','MI',V_FLAG,V_ZIP_COUNT);
    DBMS_OUTPUT.PUT_LINE('FLAG: '
    || V_FLAG);
    DBMS_OUTPUT.PUT_LINE('ZIPNUM: '
    || V_ZIP_COUNT);
END;
/
SELECT * FROM ZIPCODE WHERE STATE = 'MI';
ROLLBACK;

DECLARE
    V_FLAG        VARCHAR2(7);
    V_ZIP_COUNT   NUMBER;
BEGIN
    ADD_ZIP2('48104','Ann Arbor','MI',V_FLAG,V_ZIP_COUNT);
    DBMS_OUTPUT.PUT_LINE('FLAG: '
    || V_FLAG);
    DBMS_OUTPUT.PUT_LINE('ZIPNUM: '
    || V_ZIP_COUNT);
END;
/
SELECT * FROM ZIPCODE WHERE STATE = 'MI';