/*Marco Beltempo
12/13/2017
DBS501AA*/

set DEFINE off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DBS501_173A03"."MINE" 
(P_DATE IN VARCHAR2,
  P_TYPE IN CHAR
) AS 
V_COUNT NUMBER;
E_WRONG_TYPE EXCEPTION;
BEGIN
DBMS_OUTPUT.PUT_LINE('Last day of the month is: ' || P_DATE || ' is a ' || TO_CHAR(LAST_DAY(TO_DATE(P_DATE,'MM/YY')),'DAY'));
IF P_TYPE NOT LIKE 'P' AND P_TYPE NOT LIKE 'F' AND P_TYPE NOT LIKE 'B' THEN 
RAISE E_WRONG_TYPE;
ELSE 
SELECT COUNT(*) INTO V_COUNT FROM ALL_OBJECTS WHERE SUBSTR(OBJECT_TYPE, 0,1) LIKE UPPER(P_TYPE);
DBMS_OUTPUT.PUT_LINE('Number of stored objects of type ' || P_TYPE || ' is ' || V_COUNT); 
END IF;
EXCEPTION
WHEN E_WRONG_TYPE THEN
DBMS_OUTPUT.PUT_LINE('You have entered an Invalid letter for the stored object. Try P, F or B.');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('You have entered an Invalid FORMAT for the MONTH and YEAR. Try MM/YY.');
END MINE;
/